package com.signalnotes.blog.controller;

import com.signalnotes.blog.domain.*;
import com.signalnotes.blog.repository.*;
import com.signalnotes.blog.service.*;
import jakarta.persistence.EntityNotFoundException;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;
import java.time.Instant;
import java.time.LocalDate;
import java.util.*;

@RestController @RequestMapping("/api/admin")
public class AdminController {
    private final PostService postService; private final PostRepository posts; private final CommentRepository comments; private final SubscriptionRepository subscriptions; private final UserRepository users; private final SettingRepository settings; private final AuditLogRepository logs; private final CategoryRepository categories; private final TagRepository tags; private final BackupService backups; private final AuditService audit;
    public AdminController(PostService postService, PostRepository posts, CommentRepository comments, SubscriptionRepository subscriptions, UserRepository users, SettingRepository settings, AuditLogRepository logs, CategoryRepository categories, TagRepository tags, BackupService backups, AuditService audit) { this.postService=postService;this.posts=posts;this.comments=comments;this.subscriptions=subscriptions;this.users=users;this.settings=settings;this.logs=logs;this.categories=categories;this.tags=tags;this.backups=backups;this.audit=audit; }

    @GetMapping("/dashboard") public Map<String,Object> dashboard() { Map<String,Object> value=new LinkedHashMap<>();value.put("posts",posts.count());value.put("published",posts.countByStatus(PostStatus.PUBLISHED));value.put("drafts",posts.countByStatus(PostStatus.DRAFT));value.put("pendingComments",comments.countByStatus(CommentStatus.PENDING));value.put("subscribers",subscriptions.count());value.put("users",users.count());value.put("views",posts.findAll().stream().mapToLong(Post::getViews).sum());value.put("errors",logs.countByResult("FAILED"));value.put("popular",posts.findTop5ByStatusOrderByViewsDesc(PostStatus.PUBLISHED).stream().map(post->Map.of("id",post.getId(),"title",post.getTitle(),"views",post.getViews(),"updatedAt",post.getUpdatedAt())).toList());value.put("trend",java.util.stream.IntStream.rangeClosed(0,6).mapToObj(offset->{LocalDate day=LocalDate.now().minusDays(6-offset);long published=posts.findAll().stream().filter(post->day.equals(post.getPublishedAt())).count();return Map.of("date",day.toString(),"published",published);}).toList());value.put("status","UP");return value; }
    @GetMapping("/posts") public List<PostService.PostView> postList() { return postService.all(); }
    @PostMapping("/posts") @ResponseStatus(HttpStatus.CREATED) public PostService.PostView create(@Valid @RequestBody PostService.PostInput input, Authentication auth) { PostService.PostView value=postService.save(null,input);audit.log(auth.getName(),"CREATE_POST",value.slug());return value; }
    @PutMapping("/posts/{id}") public PostService.PostView update(@PathVariable Long id,@Valid @RequestBody PostService.PostInput input,Authentication auth){PostService.PostView value=postService.save(id,input);audit.log(auth.getName(),"UPDATE_POST",value.slug());return value;}
    @DeleteMapping("/posts/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void delete(@PathVariable Long id,Authentication auth){postService.delete(id);audit.log(auth.getName(),"DELETE_POST",id.toString());}
    @PatchMapping("/posts/batch") public Map<String,Object> batchPosts(@RequestBody BatchPostRequest input,Authentication auth){List<Post> values=posts.findAllById(input.ids());values.forEach(post->{post.setStatus(input.status());post.setDeletedAt(input.status()==PostStatus.TRASHED?Instant.now():null);});posts.saveAll(values);audit.log(auth.getName(),"BATCH_POST_STATUS",input.status()+":"+values.size());return Map.of("updated",values.size(),"status",input.status());}
    @GetMapping("/posts/{id}/revisions") public List<Map<String,Object>> revisions(@PathVariable Long id){return postService.revisions(id).stream().map(item->Map.<String,Object>of("id",item.getId(),"versionNo",item.getVersionNo(),"title",item.getTitle(),"status",item.getStatus(),"editor",item.getEditor(),"changeSummary",item.getChangeSummary(),"createdAt",item.getCreatedAt())).toList();}
    @PostMapping("/posts/{id}/revisions/{revisionId}/restore") public PostService.PostView restore(@PathVariable Long id,@PathVariable Long revisionId,Authentication auth){PostService.PostView value=postService.restoreRevision(id,revisionId);audit.log(auth.getName(),"RESTORE_POST_REVISION",revisionId.toString());return value;}

    @GetMapping("/categories") public List<Category> categories(){return categories.findAll();}
    @PostMapping("/categories") @ResponseStatus(HttpStatus.CREATED) public Category createCategory(@Valid @RequestBody Category input,Authentication auth){input.setId(null);if(categories.findByName(input.getName()).isPresent())throw new IllegalArgumentException("分类名称已存在");input.setSlug(input.getSlug()==null||input.getSlug().isBlank()?"category-"+Integer.toUnsignedString(input.getName().hashCode(),36):input.getSlug());Category value=categories.save(input);audit.log(auth.getName(),"CREATE_CATEGORY",value.getSlug());return value;}
    @PutMapping("/categories/{id}") public Category updateCategory(@PathVariable Long id,@Valid @RequestBody Category input,Authentication auth){Category value=categories.findById(id).orElseThrow(()->new EntityNotFoundException("分类不存在"));value.setName(input.getName());value.setSlug(input.getSlug());value.setDescription(input.getDescription());audit.log(auth.getName(),"UPDATE_CATEGORY",id.toString());return categories.save(value);}
    @DeleteMapping("/categories/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void deleteCategory(@PathVariable Long id,Authentication auth){Category value=categories.findById(id).orElseThrow(()->new EntityNotFoundException("分类不存在"));if(posts.findAll().stream().anyMatch(post->post.getCategory()!=null&&post.getCategory().getId().equals(id)))throw new IllegalArgumentException("分类仍被文章引用，请先迁移文章");categories.delete(value);audit.log(auth.getName(),"DELETE_CATEGORY",id.toString());}
    @GetMapping("/tags") public List<Tag> tags(){return tags.findAll();}
    @PostMapping("/tags") @ResponseStatus(HttpStatus.CREATED) public Tag createTag(@Valid @RequestBody Tag input,Authentication auth){input.setId(null);if(tags.findByName(input.getName()).isPresent())throw new IllegalArgumentException("标签名称已存在");if(input.getSlug()==null||input.getSlug().isBlank())input.setSlug("tag-"+Integer.toUnsignedString(input.getName().hashCode(),36));Tag value=tags.save(input);audit.log(auth.getName(),"CREATE_TAG",value.getSlug());return value;}
    @PutMapping("/tags/{id}") public Tag updateTag(@PathVariable Long id,@Valid @RequestBody Tag input,Authentication auth){Tag value=tags.findById(id).orElseThrow(()->new EntityNotFoundException("标签不存在"));String previous=value.getName();value.setName(input.getName());value.setSlug(input.getSlug());value.setDescription(input.getDescription());if(!previous.equals(input.getName()))posts.findAll().forEach(post->{if(post.getTags().remove(previous)){post.getTags().add(input.getName());posts.save(post);}});audit.log(auth.getName(),"UPDATE_TAG",id.toString());return tags.save(value);}
    @DeleteMapping("/tags/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void deleteTag(@PathVariable Long id,Authentication auth){Tag value=tags.findById(id).orElseThrow(()->new EntityNotFoundException("标签不存在"));if(posts.findAll().stream().anyMatch(post->post.getTags().contains(value.getName())))throw new IllegalArgumentException("标签仍被文章引用，请先迁移文章");tags.delete(value);audit.log(auth.getName(),"DELETE_TAG",id.toString());}

    @GetMapping("/comments") public List<Comment> commentList(){return comments.findAllByOrderByCreatedAtDesc();}
    @PatchMapping("/comments/{id}") public Comment moderate(@PathVariable Long id,@RequestBody Map<String,String> body,Authentication auth){Comment value=comments.findById(id).orElseThrow(()->new EntityNotFoundException("评论不存在"));value.setStatus(CommentStatus.valueOf(body.getOrDefault("status","PENDING")));audit.log(auth.getName(),"MODERATE_COMMENT",id.toString());return comments.save(value);}
    @PostMapping("/comments/{id}/reply") @ResponseStatus(HttpStatus.CREATED) public Comment reply(@PathVariable Long id,@RequestBody Map<String,String> body,Authentication auth){Comment parent=comments.findById(id).orElseThrow(()->new EntityNotFoundException("评论不存在"));String content=body.getOrDefault("content","").trim();if(content.length()<2||content.length()>2000)throw new IllegalArgumentException("回复需为 2-2000 个字");parent.setStatus(CommentStatus.APPROVED);comments.save(parent);Comment value=new Comment();value.setParentId(parent.getId());value.setPostSlug(parent.getPostSlug());value.setAuthorName("站点管理员");value.setContent(content);value.setStatus(CommentStatus.APPROVED);value=comments.save(value);audit.log(auth.getName(),"REPLY_COMMENT",id.toString());return value;}
    @DeleteMapping("/comments/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void deleteComment(@PathVariable Long id){comments.deleteById(id);}

    @GetMapping("/users") public List<SiteUser> userList(){return users.findAll();}
    @PatchMapping("/users/{id}") public SiteUser updateUser(@PathVariable Long id,@RequestBody Map<String,String> body,Authentication auth){SiteUser value=users.findById(id).orElseThrow(()->new EntityNotFoundException("用户不存在"));if(body.containsKey("role"))value.setRole(body.get("role"));if(body.containsKey("status"))value.setStatus(body.get("status"));audit.log(auth.getName(),"UPDATE_USER",id.toString());return users.save(value);}

    @GetMapping("/settings") public Map<String,String> getSettings(){Map<String,String> result=new LinkedHashMap<>();settings.findAll().forEach(item->result.put(item.getKey(),item.getValue()));return result;}
    @PutMapping("/settings") public Map<String,String> saveSettings(@RequestBody Map<String,String> input,Authentication auth){input.forEach((key,value)->{SiteSetting item=settings.findById(key).orElseGet(SiteSetting::new);item.setKey(key);item.setValue(value);settings.save(item);});audit.log(auth.getName(),"UPDATE_SETTINGS",String.join(",",input.keySet()));return input;}
    @GetMapping("/logs") public List<AuditLog> logList(){return logs.findTop50ByOrderByCreatedAtDesc();}
    @GetMapping("/backups") public List<BackupJob> backups(){return backups.list();}
    @PostMapping("/backups") public BackupJob backup(Authentication auth){BackupJob value=backups.create();audit.log(auth.getName(),"CREATE_BACKUP",value.getFilename());return value;}
    public record BatchPostRequest(Set<Long> ids, PostStatus status) {}
}
