package com.signalnotes.blog.controller;

import com.signalnotes.blog.domain.*;
import com.signalnotes.blog.repository.*;
import com.signalnotes.blog.service.*;
import jakarta.persistence.EntityNotFoundException;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.security.core.Authentication;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;
import java.time.Instant;
import java.time.LocalDate;
import java.util.*;

@RestController @RequestMapping("/api/admin")
public class AdminController {
    private final PostService postService; private final PostRepository posts; private final CommentRepository comments; private final ContactMessageRepository contactMessages; private final SubscriptionRepository subscriptions; private final UserRepository users; private final SettingRepository settings; private final AuditLogRepository logs; private final CategoryRepository categories; private final TagRepository tags; private final BackupService backups; private final AuditService audit; private final NotificationMailService mail; private final PasswordEncoder passwordEncoder;
    public AdminController(PostService postService, PostRepository posts, CommentRepository comments, ContactMessageRepository contactMessages, SubscriptionRepository subscriptions, UserRepository users, SettingRepository settings, AuditLogRepository logs, CategoryRepository categories, TagRepository tags, BackupService backups, AuditService audit, NotificationMailService mail, PasswordEncoder passwordEncoder) { this.postService=postService;this.posts=posts;this.comments=comments;this.contactMessages=contactMessages;this.subscriptions=subscriptions;this.users=users;this.settings=settings;this.logs=logs;this.categories=categories;this.tags=tags;this.backups=backups;this.audit=audit;this.mail=mail;this.passwordEncoder=passwordEncoder; }

    @GetMapping("/dashboard") public Map<String,Object> dashboard() { Map<String,Object> value=new LinkedHashMap<>();value.put("posts",posts.count());value.put("published",posts.countByStatus(PostStatus.PUBLISHED));value.put("drafts",posts.countByStatus(PostStatus.DRAFT));value.put("pendingComments",comments.countByStatus(CommentStatus.PENDING));value.put("subscribers",subscriptions.count());value.put("users",users.count());value.put("views",posts.findAll().stream().mapToLong(Post::getViews).sum());value.put("errors",logs.countByResult("FAILED"));value.put("popular",posts.findTop5ByStatusOrderByViewsDesc(PostStatus.PUBLISHED).stream().map(post->Map.of("id",post.getId(),"title",post.getTitle(),"views",post.getViews(),"updatedAt",post.getUpdatedAt())).toList());value.put("trend",java.util.stream.IntStream.rangeClosed(0,6).mapToObj(offset->{LocalDate day=LocalDate.now().minusDays(6-offset);long published=posts.findAll().stream().filter(post->day.equals(post.getPublishedAt())).count();return Map.of("date",day.toString(),"published",published);}).toList());value.put("status","UP");return value; }
    @GetMapping("/me") public Map<String,String> me(Authentication auth){SiteUser user=users.findByLoginName(auth.getName()).orElseThrow(()->new EntityNotFoundException("用户不存在"));return Map.of("loginName",user.getLoginName(),"name",user.getName(),"role",user.getRole(),"status",user.getStatus());}
    @GetMapping("/posts") public List<PostService.PostView> postList() { return postService.all(); }
    @PostMapping("/posts") @ResponseStatus(HttpStatus.CREATED) public PostService.PostView create(@Valid @RequestBody PostService.PostInput input, Authentication auth) { PostService.PostView value=postService.save(null,input);audit.log(auth.getName(),"CREATE_POST",value.slug());return value; }
    @PutMapping("/posts/{id}") public PostService.PostView update(@PathVariable Long id,@Valid @RequestBody PostService.PostInput input,Authentication auth){PostService.PostView value=postService.save(id,input);audit.log(auth.getName(),"UPDATE_POST",value.slug());return value;}
    @DeleteMapping("/posts/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void delete(@PathVariable Long id,@RequestParam(defaultValue="false") boolean permanent,Authentication auth){if(permanent){postService.permanentlyDelete(id);audit.log(auth.getName(),"PERMANENTLY_DELETE_POST",id.toString());}else{postService.delete(id);audit.log(auth.getName(),"DELETE_POST",id.toString());}}
    @PostMapping("/posts/{id}/restore") public PostService.PostView restorePost(@PathVariable Long id,Authentication auth){PostService.PostView value=postService.restore(id);audit.log(auth.getName(),"RESTORE_POST",id.toString());return value;}
    @PatchMapping("/posts/batch") public Map<String,Object> batchPosts(@RequestBody BatchPostRequest input,Authentication auth){List<Post> values=posts.findAllById(input.ids());values.forEach(post->{post.setStatus(input.status());if(input.status()==PostStatus.PUBLISHED&&post.getPublishedAt()==null)post.setPublishedAt(LocalDate.now());post.setUpdatedAt(LocalDate.now());post.setDeletedAt(input.status()==PostStatus.TRASHED?Instant.now():null);});posts.saveAll(values);audit.log(auth.getName(),"BATCH_POST_STATUS",input.status()+":"+values.size());return Map.of("updated",values.size(),"status",input.status());}
    @GetMapping("/posts/{id}/revisions") public List<Map<String,Object>> revisions(@PathVariable Long id){return postService.revisions(id).stream().map(item->Map.<String,Object>of("id",item.getId(),"versionNo",item.getVersionNo(),"title",item.getTitle(),"status",item.getStatus(),"editor",item.getEditor(),"changeSummary",item.getChangeSummary(),"createdAt",item.getCreatedAt())).toList();}
    @PostMapping("/posts/{id}/revisions/{revisionId}/restore") public PostService.PostView restore(@PathVariable Long id,@PathVariable Long revisionId,Authentication auth){PostService.PostView value=postService.restoreRevision(id,revisionId);audit.log(auth.getName(),"RESTORE_POST_REVISION",revisionId.toString());return value;}

    @GetMapping("/categories") public List<Category> categories(){return categories.findAll();}
    @PostMapping("/categories") @ResponseStatus(HttpStatus.CREATED) public Category createCategory(@Valid @RequestBody Category input,Authentication auth){input.setId(null);if(categories.findByName(input.getName()).isPresent())throw new IllegalArgumentException("分类名称已存在");input.setSlug(input.getSlug()==null||input.getSlug().isBlank()?"category-"+Integer.toUnsignedString(input.getName().hashCode(),36):input.getSlug());Category value=categories.save(input);audit.log(auth.getName(),"CREATE_CATEGORY",value.getSlug());return value;}
    @PutMapping("/categories/{id}") public Category updateCategory(@PathVariable Long id,@Valid @RequestBody Category input,Authentication auth){Category value=categories.findById(id).orElseThrow(()->new EntityNotFoundException("分类不存在"));value.setName(input.getName());value.setSlug(input.getSlug());value.setDescription(input.getDescription());audit.log(auth.getName(),"UPDATE_CATEGORY",id.toString());return categories.save(value);}
    @DeleteMapping("/categories/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void deleteCategory(@PathVariable Long id,Authentication auth){Category value=categories.findById(id).orElseThrow(()->new EntityNotFoundException("分类不存在"));if(posts.findAll().stream().anyMatch(post->post.getCategory()!=null&&post.getCategory().getId().equals(id)))throw new IllegalArgumentException("分类仍被文章引用，请先迁移文章");categories.delete(value);audit.log(auth.getName(),"DELETE_CATEGORY",id.toString());}
    @GetMapping("/tags") public List<Tag> tags(){return tags.findAll();}
    @PostMapping("/tags") @ResponseStatus(HttpStatus.CREATED) public Tag createTag(@Valid @RequestBody Tag input,Authentication auth){input.setId(null);if(tags.findByName(input.getName()).isPresent())throw new IllegalArgumentException("标签名称已存在");if(input.getSlug()==null||input.getSlug().isBlank())input.setSlug("tag-"+Integer.toUnsignedString(input.getName().hashCode(),36));Tag value=tags.save(input);audit.log(auth.getName(),"CREATE_TAG",value.getSlug());return value;}
    @Transactional @PutMapping("/tags/{id}") public Tag updateTag(@PathVariable Long id,@Valid @RequestBody Tag input,Authentication auth){Tag value=tags.findById(id).orElseThrow(()->new EntityNotFoundException("标签不存在"));if(tags.existsByNameAndIdNot(input.getName(),id))throw new IllegalArgumentException("标签名称已存在");if(tags.existsBySlugAndIdNot(input.getSlug(),id))throw new IllegalArgumentException("标签 slug 已存在");String previous=value.getName();value.setName(input.getName());value.setSlug(input.getSlug());value.setDescription(input.getDescription());Tag saved=tags.save(value);if(!previous.equals(input.getName())){List<Post> changed=posts.findAll().stream().filter(post->post.getTags().remove(previous)).peek(post->post.getTags().add(input.getName())).toList();posts.saveAll(changed);}audit.log(auth.getName(),"UPDATE_TAG",id.toString());return saved;}
    @DeleteMapping("/tags/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void deleteTag(@PathVariable Long id,Authentication auth){Tag value=tags.findById(id).orElseThrow(()->new EntityNotFoundException("标签不存在"));if(posts.findAll().stream().anyMatch(post->post.getTags().contains(value.getName())))throw new IllegalArgumentException("标签仍被文章引用，请先迁移文章");tags.delete(value);audit.log(auth.getName(),"DELETE_TAG",id.toString());}

    @GetMapping("/comments") public List<Comment> commentList(){return comments.findAllByOrderByCreatedAtDesc();}
    @PatchMapping("/comments/{id}") public Comment moderate(@PathVariable Long id,@RequestBody Map<String,String> body,Authentication auth){Comment value=comments.findById(id).orElseThrow(()->new EntityNotFoundException("评论不存在"));value.setStatus(CommentStatus.valueOf(body.getOrDefault("status","PENDING")));audit.log(auth.getName(),"MODERATE_COMMENT",id.toString());return comments.save(value);}
    @PostMapping("/comments/{id}/reply") @ResponseStatus(HttpStatus.CREATED) public Comment reply(@PathVariable Long id,@RequestBody Map<String,String> body,Authentication auth){Comment parent=comments.findById(id).orElseThrow(()->new EntityNotFoundException("评论不存在"));String content=body.getOrDefault("content","").trim();if(content.length()<2||content.length()>2000)throw new IllegalArgumentException("回复需为 2-2000 个字");parent.setStatus(CommentStatus.APPROVED);comments.save(parent);Comment value=new Comment();value.setParentId(parent.getId());value.setPostSlug(parent.getPostSlug());value.setAuthorName("站点管理员");value.setContent(content);value.setStatus(CommentStatus.APPROVED);value=comments.save(value);audit.log(auth.getName(),"REPLY_COMMENT",id.toString());return value;}
    @DeleteMapping("/comments/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void deleteComment(@PathVariable Long id){comments.deleteById(id);}

    @GetMapping("/users") public List<SiteUser> userList(){return users.findAll();}
    @PostMapping("/users") @ResponseStatus(HttpStatus.CREATED) public SiteUser createUser(@RequestBody Map<String,String> body,Authentication auth){String name=body.getOrDefault("name","").trim();String email=body.getOrDefault("email","").trim().toLowerCase();if(name.isBlank()||email.isBlank())throw new IllegalArgumentException("姓名和邮箱不能为空");if(users.findByEmailIgnoreCase(email).isPresent())throw new IllegalArgumentException("邮箱已存在");SiteUser value=new SiteUser();value.setName(name);value.setEmail(email);value.setRole(normalizeRole(body.getOrDefault("role","AUTHOR")));value.setStatus(normalizeUserStatus(body.getOrDefault("status","INVITED")));applyCredentials(value,body,true);value=users.save(value);audit.log(auth.getName(),"CREATE_USER",value.getEmail());return value;}
    @PatchMapping("/users/{id}") public SiteUser updateUser(@PathVariable Long id,@RequestBody Map<String,String> body,Authentication auth){return updateUserRecord(id,body,auth);}
    @PutMapping("/users/{id}") public SiteUser replaceUser(@PathVariable Long id,@RequestBody Map<String,String> body,Authentication auth){return updateUserRecord(id,body,auth);}
    @DeleteMapping("/users/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void deleteUser(@PathVariable Long id,Authentication auth){SiteUser value=users.findById(id).orElseThrow(()->new EntityNotFoundException("用户不存在"));if(value.getLoginName()!=null&&value.getLoginName().equals(auth.getName()))throw new IllegalArgumentException("不能删除当前登录用户");if("ADMIN".equals(value.getRole())&&"ACTIVE".equals(value.getStatus())&&users.findAll().stream().filter(item->"ADMIN".equals(item.getRole())&&"ACTIVE".equals(item.getStatus())).count()<=1)throw new IllegalArgumentException("不能删除最后一个启用的管理员");users.delete(value);audit.log(auth.getName(),"DELETE_USER",id.toString());}
    private SiteUser updateUserRecord(Long id,Map<String,String> body,Authentication auth){SiteUser value=users.findById(id).orElseThrow(()->new EntityNotFoundException("用户不存在"));String nextRole=body.containsKey("role")?normalizeRole(body.get("role")):value.getRole();String nextStatus=body.containsKey("status")?normalizeUserStatus(body.get("status")):value.getStatus();if("ADMIN".equals(value.getRole())&&"ACTIVE".equals(value.getStatus())&&(!"ADMIN".equals(nextRole)||!"ACTIVE".equals(nextStatus))&&users.findAll().stream().filter(item->"ADMIN".equals(item.getRole())&&"ACTIVE".equals(item.getStatus())).count()<=1)throw new IllegalArgumentException("不能停用或降级最后一个启用的管理员");if(body.containsKey("name")&&!body.get("name").isBlank())value.setName(body.get("name").trim());if(body.containsKey("email")&&!body.get("email").isBlank()){String email=body.get("email").trim().toLowerCase();users.findByEmailIgnoreCase(email).filter(item->!item.getId().equals(id)).ifPresent(item->{throw new IllegalArgumentException("邮箱已存在");});value.setEmail(email);}if(body.containsKey("loginName")&&!body.get("loginName").isBlank()){String loginName=normalizeLoginName(body.get("loginName"));users.findByLoginName(loginName).filter(item->!item.getId().equals(id)).ifPresent(item->{throw new IllegalArgumentException("登录名已存在");});value.setLoginName(loginName);}applyCredentials(value,body,false);value.setRole(nextRole);value.setStatus(nextStatus);if("ACTIVE".equals(nextStatus)&&(value.getLoginName()==null||value.getPasswordHash()==null||value.getPasswordHash().isBlank()))throw new IllegalArgumentException("启用用户需要设置登录名和至少 10 位密码");audit.log(auth.getName(),"UPDATE_USER",id.toString());return users.save(value);}
    private String normalizeRole(String role){String value=role==null?"AUTHOR":role.trim().toUpperCase();if(!Set.of("ADMIN","EDITOR","AUTHOR","VIEWER").contains(value))throw new IllegalArgumentException("不支持的用户角色");return value;}
    private void applyCredentials(SiteUser value,Map<String,String> body,boolean creating){String loginName=body.getOrDefault("loginName","").trim();String password=body.getOrDefault("password","").trim();if(!loginName.isBlank()){loginName=normalizeLoginName(loginName);users.findByLoginName(loginName).filter(item->!item.getId().equals(value.getId())).ifPresent(item->{throw new IllegalArgumentException("登录名已存在");});value.setLoginName(loginName);}if(!password.isBlank()){if(password.length()<10||password.length()>128)throw new IllegalArgumentException("密码长度需为 10-128 个字符");value.setPasswordHash(passwordEncoder.encode(password));}else if(creating&&"ACTIVE".equals(value.getStatus()))throw new IllegalArgumentException("启用用户需要设置登录名和至少 10 位密码");}
    private String normalizeLoginName(String loginName){String value=loginName==null?"":loginName.trim();if(!value.matches("[A-Za-z0-9._@-]{3,80}"))throw new IllegalArgumentException("登录名需为 3-80 位字母、数字或 ._@-");return value;}
    private String normalizeUserStatus(String status){String value=status==null?"INVITED":status.trim().toUpperCase();if(!Set.of("ACTIVE","DISABLED","INVITED").contains(value))throw new IllegalArgumentException("不支持的用户状态");return value;}

    @GetMapping("/contact-messages") public List<ContactMessage> contactList(){return contactMessages.findAll(org.springframework.data.domain.Sort.by(org.springframework.data.domain.Sort.Direction.DESC,"createdAt"));}
    @PatchMapping("/contact-messages/{id}") public ContactMessage updateContact(@PathVariable Long id,@RequestBody Map<String,String> body,Authentication auth){ContactMessage value=contactMessages.findById(id).orElseThrow(()->new EntityNotFoundException("反馈不存在"));String status=body.getOrDefault("status",value.getStatus()).toUpperCase();if(!Set.of("RECEIVED","IN_PROGRESS","RESOLVED","ARCHIVED").contains(status))throw new IllegalArgumentException("不支持的反馈状态");value.setStatus(status);audit.log(auth.getName(),"UPDATE_CONTACT_MESSAGE",id.toString());return contactMessages.save(value);}
    @DeleteMapping("/contact-messages/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void deleteContact(@PathVariable Long id,Authentication auth){contactMessages.deleteById(id);audit.log(auth.getName(),"DELETE_CONTACT_MESSAGE",id.toString());}
    @GetMapping("/subscriptions") public List<Subscription> subscriptionList(){return subscriptions.findAllByOrderByCreatedAtDesc();}
    @PatchMapping("/subscriptions/{id}") public Subscription updateSubscription(@PathVariable Long id,@RequestBody Map<String,String> body,Authentication auth){Subscription value=subscriptions.findById(id).orElseThrow(()->new EntityNotFoundException("订阅不存在"));String status=body.getOrDefault("status",value.getStatus()).toUpperCase();if(!Set.of("PENDING","CONFIRMED","UNSUBSCRIBED").contains(status))throw new IllegalArgumentException("不支持的订阅状态");value.setStatus(status);audit.log(auth.getName(),"UPDATE_SUBSCRIPTION",id.toString());return subscriptions.save(value);}
    @DeleteMapping("/subscriptions/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void deleteSubscription(@PathVariable Long id,Authentication auth){subscriptions.deleteById(id);audit.log(auth.getName(),"DELETE_SUBSCRIPTION",id.toString());}
    @PostMapping("/email/test") public Map<String,Object> testEmail(@RequestBody Map<String,String> body,Authentication auth){String recipient=body.getOrDefault("to","").trim();mail.validateRecipient(recipient);boolean sent=mail.sendTest(recipient);audit.log(auth.getName(),"TEST_EMAIL",recipient);return Map.of("sent",sent,"configured",mail.isConfigured(),"message",sent?"测试邮件已发送":mail.isConfigured()?"邮件发送失败，请检查 SMTP 配置":"邮件服务尚未配置");}

    @GetMapping("/settings") public Map<String,String> getSettings(){Map<String,String> result=new LinkedHashMap<>();settings.findAll().forEach(item->{if(SiteSettingPolicy.isAllowed(item.getKey())&&!"mail.password".equals(item.getKey()))result.put(item.getKey(),item.getValue()==null?"":item.getValue());});result.put("mail.password","");result.put("mail.passwordConfigured",Boolean.toString(settings.findById("mail.password").map(item->item.getValue()!=null&&!item.getValue().isBlank()).orElse(false)));return result;}
    @Transactional @PutMapping("/settings") public Map<String,String> saveSettings(@RequestBody Map<String,String> input,Authentication auth){Map<String,String> normalized=SiteSettingPolicy.validateAndNormalize(input);Map<String,String> prepared=mail.prepareSettings(normalized);Map<String,String> result=new LinkedHashMap<>();prepared.forEach((key,value)->{if("mail.password".equals(key)&&value.isBlank()){result.put(key,"");return;}SiteSetting item=settings.findById(key).orElseGet(SiteSetting::new);item.setKey(key);item.setValue(value==null?"":value);settings.save(item);result.put(key,"mail.password".equals(key)?"":item.getValue());});result.put("mail.passwordConfigured",Boolean.toString(settings.findById("mail.password").map(item->item.getValue()!=null&&!item.getValue().isBlank()).orElse(false)));audit.log(auth.getName(),"UPDATE_SETTINGS",String.join(",",normalized.keySet()));return result;}
    @GetMapping("/logs") public List<AuditLog> logList(){return logs.findTop50ByOrderByCreatedAtDesc();}
    @GetMapping("/backups") public List<BackupJob> backups(){return backups.list();}
    @PostMapping("/backups") public BackupJob backup(Authentication auth){BackupJob value=backups.create();audit.log(auth.getName(),"CREATE_BACKUP",value.getFilename());return value;}
    public record BatchPostRequest(Set<Long> ids, PostStatus status) {}
}
