<script setup>
import { Activity, Archive, ArrowLeft, ArrowRight, BarChart3, Check, ClipboardList, FileText, Image as ImageIcon, LayoutDashboard, LogOut, Menu, Plus, RefreshCw, Save, Search, Settings, ShieldCheck, Trash2, Upload, Users, X } from 'lucide-vue-next';
import { computed, onMounted, ref, watch } from 'vue'; import { useRoute, useRouter } from 'vue-router';
import { categories, posts } from '../data'; import { adminRequest, apiRequest, createAdminToken } from '../api';

const route=useRoute();const router=useRouter();const authed=ref(localStorage.getItem('signal-admin-auth')==='true');const login=ref({email:'admin',password:'signal2026'});const loginError=ref('');const menuOpen=ref(false);const apiStatus=ref('本地数据');
const adminPosts=ref(JSON.parse(localStorage.getItem('signal-admin-posts')||'null')||posts.map(p=>({...p,status:'PUBLISHED'})));const query=ref('');const filter=ref('ALL');const users=ref([{id:1,name:'林默',email:'admin@signal.local',role:'管理员',status:'正常'},{id:2,name:'编辑同事',email:'editor@signal.local',role:'编辑',status:'正常'},{id:3,name:'测试读者',email:'reader@example.com',role:'访客',status:'待确认'}]);
const comments=ref([{id:1,authorName:'访客',content:'希望继续写更多真实项目里的 AI 经验。',postSlug:'building-reliable-ai-systems',status:'PENDING'},{id:2,authorName:'测试读者',content:'Local-first 的部分很有启发。',postSlug:'local-first-software',status:'PENDING'}]);const media=ref([]);const settings=ref(JSON.parse(localStorage.getItem('signal-settings')||'{"siteName":"脉冲笔记","tagline":"把复杂技术讲清楚","shareTemplate":"横版卡片","comments":true}'));const saved=ref('');const backup=ref('今天 04:00');
const nav=[['/admin','仪表盘',LayoutDashboard],['/admin/posts','文章',FileText],['/admin/media','媒体库',ImageIcon],['/admin/comments','评论',ClipboardList],['/admin/users','用户',Users],['/admin/settings','设置',Settings],['/admin/logs','日志与备份',Activity]];
const section=computed(()=>route.path.split('/')[2]||'dashboard');const editorMode=computed(()=>route.path.includes('/posts/new')||route.path.includes('/edit'));const filteredPosts=computed(()=>adminPosts.value.filter(p=>(!query.value||p.title.includes(query.value))&&(filter.value==='ALL'||p.status===filter.value)));
const editId=computed(()=>route.params.pathMatch?.[1]);const editor=ref({});
function syncEditor(){if(!editorMode.value)return;const id=editId.value;const existing=id?adminPosts.value.find(p=>String(p.id)===String(id)):null;editor.value=existing?{...existing}:{id:`post-${Date.now()}`,title:'',slug:'',excerpt:'',content:'',category:'人工智能',tags:[],status:'DRAFT',cover:'/assets/hero-circuit.jpg',coverAlt:'',readMinutes:5};}
watch(()=>route.path,()=>{menuOpen.value=false;syncEditor();},{immediate:true});
onMounted(async()=>{if(authed.value) await loadAdminData();});
async function loadAdminData(){try{const [dashboard,postData,commentData,userData,settingData,mediaData]=await Promise.all([adminRequest('/admin/dashboard'),adminRequest('/admin/posts'),adminRequest('/admin/comments'),adminRequest('/admin/users'),adminRequest('/admin/settings'),apiRequest('/media')]);adminPosts.value=postData;comments.value=commentData;users.value=userData;settings.value={...settings.value,...settingData};media.value=mediaData||[];apiStatus.value=`MySQL 已连接 · ${dashboard.posts} 篇文章`;syncEditor();}catch{apiStatus.value='后端未连接 · 本地模式';}}
async function doLogin(){loginError.value='';const token=createAdminToken(login.value.email,login.value.password);try{localStorage.setItem('signal-admin-token',token);await apiRequest('/admin/dashboard',{headers:{Authorization:`Basic ${token}`}});authed.value=true;localStorage.setItem('signal-admin-auth','true');await loadAdminData();}catch{localStorage.removeItem('signal-admin-token');if((login.value.email==='admin'||login.value.email==='admin@signal.local')&&login.value.password==='signal2026'){authed.value=true;localStorage.setItem('signal-admin-auth','true');apiStatus.value='后端未连接 · 本地模式';}else loginError.value='账号或密码不正确';}}
function logout(){authed.value=false;localStorage.removeItem('signal-admin-auth');localStorage.removeItem('signal-admin-token');router.push('/admin');}
function persist(){localStorage.setItem('signal-admin-posts',JSON.stringify(adminPosts.value));}
async function savePost(status=editor.value.status){const value={...editor.value,status,updatedAt:new Date().toISOString().slice(0,10),publishedAt:editor.value.publishedAt||new Date().toISOString().slice(0,10),tags:Array.isArray(editor.value.tags)?editor.value.tags:String(editor.value.tags||'').split(',').map(t=>t.trim()).filter(Boolean)};try{const payload={slug:value.slug||value.title.toLowerCase().replace(/\s+/g,'-'),title:value.title,excerpt:value.excerpt||'',content:value.content||'',cover:value.cover,coverAlt:value.coverAlt,category:value.category,tags:value.tags,status:value.status,authorName:'林默',publishedAt:value.publishedAt,readMinutes:Number(value.readMinutes)||5};const result=value.id&&Number.isFinite(Number(value.id))?await adminRequest(`/admin/posts/${value.id}`,{method:'PUT',body:JSON.stringify(payload)}):await adminRequest('/admin/posts',{method:'POST',body:JSON.stringify(payload)});Object.assign(value,result);apiStatus.value='MySQL 已连接';}catch{apiStatus.value='后端未连接 · 已保存到本地';}const i=adminPosts.value.findIndex(p=>String(p.id)===String(value.id));if(i>=0)adminPosts.value[i]=value;else adminPosts.value.unshift(value);persist();saved.value=status==='PUBLISHED'?'文章已发布':'草稿已保存';setTimeout(()=>{saved.value='';if(status==='PUBLISHED')router.push('/admin/posts');},500);}
async function saveSettings(){try{await adminRequest('/admin/settings',{method:'PUT',body:JSON.stringify(settings.value)});apiStatus.value='MySQL 已连接';}catch{localStorage.setItem('signal-settings',JSON.stringify(settings.value));}saved.value='设置已保存';setTimeout(()=>saved.value='',1800);}
async function moderate(item,status){item.status=status;try{await adminRequest(`/admin/comments/${item.id}`,{method:'PATCH',body:JSON.stringify({status})});}catch{}}
async function deleteComment(item){comments.value=comments.value.filter(c=>c.id!==item.id);try{await adminRequest(`/admin/comments/${item.id}`,{method:'DELETE'});}catch{}}
async function uploadMedia(event){for(const file of event.target.files||[]){try{const body=new FormData();body.append('file',file);const result=await adminRequest('/admin/media',{method:'POST',headers:{},body});media.value.unshift(result);}catch{}}event.target.value='';}
</script>

<template>
  <main v-if="!authed" class="admin-login"><div class="admin-login-mark"><span /><span /><span /></div><span class="admin-kicker">SIGNAL NOTES / ADMIN</span><h1>管理你的<br />技术记录。</h1><p>发布文章、整理媒体和处理读者反馈。</p><form @submit.prevent="doLogin"><label>管理员账号<input v-model="login.email" autocomplete="username" /></label><label>密码<input v-model="login.password" type="password" autocomplete="current-password" /></label><button class="button button-primary">进入后台 <ArrowRight :size="17" /></button><small v-if="loginError">{{loginError}}</small></form><span class="admin-demo-hint">演示账号：admin / signal2026</span></main>
  <div v-else class="admin-shell"><aside :class="{'is-open':menuOpen}"><div class="admin-aside-brand"><span class="brand-mark"><i /><i /><i /></span><div><b>脉冲笔记</b><small>ADMIN / CONSOLE</small></div></div><nav><RouterLink v-for="item in nav" :key="item[0]" :to="item[0]"><component :is="item[2]" :size="17" />{{item[1]}}<em v-if="item[1]==='评论'">{{comments.filter(c=>c.status==='PENDING').length}}</em></RouterLink></nav><div class="admin-aside-bottom"><RouterLink to="/blog"><ArrowRight :size="15" />查看站点</RouterLink><button @click="logout"><LogOut :size="15" />退出登录</button></div></aside><div class="admin-body"><header class="admin-topbar"><button class="admin-menu-toggle" @click="menuOpen=!menuOpen"><X v-if="menuOpen" :size="19" /><Menu v-else :size="19" /></button><div class="admin-breadcrumb">ADMIN <span>/</span> SIGNAL NOTES</div><div class="admin-top-actions"><span class="admin-online"><i />{{apiStatus}}</span><span class="admin-user">林默 · 管理员</span></div></header>
    <main v-if="editorMode" class="admin-content editor-page"><div class="editor-top"><RouterLink to="/admin/posts"><ArrowLeft :size="16" />文章列表</RouterLink><div><span>{{saved||'未保存修改'}}</span><button class="button" @click="savePost('DRAFT')"><Save :size="15" />保存草稿</button><button class="button button-primary" @click="savePost('PUBLISHED')">发布 <ArrowRight :size="15" /></button></div></div><div class="editor-grid"><section class="editor-main"><input v-model="editor.title" class="editor-title" placeholder="文章标题" /><textarea v-model="editor.excerpt" class="editor-excerpt" rows="3" placeholder="写一段摘要" /><textarea v-model="editor.content" class="editor-content" placeholder="使用 Markdown 写作..." /></section><aside class="editor-sidebar"><div class="editor-card"><h3>发布设置</h3><label>状态<select v-model="editor.status"><option value="DRAFT">草稿</option><option value="PENDING">待审核</option><option value="PUBLISHED">已发布</option></select></label><label>分类<select v-model="editor.category"><option v-for="cat in categories" :key="cat.name">{{cat.name}}</option></select></label><label>标签<input v-model="editor.tags" placeholder="AI, 工程" /></label><label>预计阅读分钟<input v-model.number="editor.readMinutes" type="number" min="1" /></label></div><div class="editor-card"><h3>SEO 与媒体</h3><label>Slug<input v-model="editor.slug" /></label><label>封面 URL<input v-model="editor.cover" /></label><label>图片替代文本<input v-model="editor.coverAlt" /></label></div></aside></div></main>
    <main v-else class="admin-content">
      <template v-if="section==='dashboard'"><header class="admin-page-header"><div><span>OVERVIEW / 001</span><h1>早上好，林默。</h1><p>这里是你的内容工作台，今天也保持一点信号。</p></div><RouterLink class="button button-primary" to="/admin/posts/new"><Plus :size="17" />新建文章</RouterLink></header><section class="admin-stat-grid"><div class="admin-stat"><FileText :size="18" /><span>已发布文章</span><strong>{{adminPosts.filter(p=>p.status==='PUBLISHED').length}}</strong><small>内容持续更新</small></div><div class="admin-stat"><ClipboardList :size="18" /><span>待处理评论</span><strong>{{comments.filter(c=>c.status==='PENDING').length}}</strong><small>需要审核</small></div><div class="admin-stat"><Archive :size="18" /><span>草稿</span><strong>{{adminPosts.filter(p=>p.status==='DRAFT').length}}</strong><small>继续编辑</small></div><div class="admin-stat"><BarChart3 :size="18" /><span>近 7 日访问</span><strong>2,418</strong><small>+18.4%</small></div></section><section class="admin-panel chart-panel"><div class="panel-heading"><div><span>RECENT NOTES</span><h2>最近文章</h2></div><RouterLink to="/admin/posts">查看全部</RouterLink></div><div class="admin-table compact"><RouterLink v-for="post in adminPosts.slice(0,6)" :key="post.id" class="table-row" :to="`/admin/posts/${post.id}/edit`"><strong>{{post.title}}</strong><span>{{post.category}}</span><span class="status">{{post.status}}</span><time>{{post.updatedAt}}</time></RouterLink></div></section></template>
      <template v-else-if="section==='posts'"><header class="admin-page-header"><div><span>CONTENT / POSTS</span><h1>文章</h1><p>{{adminPosts.length}} 篇内容，按状态和更新时间管理。</p></div><RouterLink class="button button-primary" to="/admin/posts/new"><Plus :size="17" />新建文章</RouterLink></header><div class="admin-toolbar"><div class="admin-search"><Search :size="16" /><input v-model="query" placeholder="搜索标题" /></div><div class="segmented"><button v-for="item in ['ALL','PUBLISHED','DRAFT','PENDING']" :key="item" :class="{active:filter===item}" @click="filter=item">{{item}}</button></div></div><section class="admin-panel"><div class="admin-table post-admin-table"><div class="table-head"><span>文章</span><span>分类</span><span>状态</span><span>更新时间</span><span>操作</span></div><div v-for="post in filteredPosts" :key="post.id" class="table-row"><RouterLink :to="`/admin/posts/${post.id}/edit`"><strong>{{post.title}}</strong><small>{{post.excerpt}}</small></RouterLink><span>{{post.category}}</span><span class="status">{{post.status}}</span><time>{{post.updatedAt}}</time><RouterLink :to="`/admin/posts/${post.id}/edit`"><FileText :size="15" /></RouterLink></div></div></section></template>
      <template v-else-if="section==='media'"><header class="admin-page-header"><div><span>LIBRARY / MEDIA</span><h1>媒体库</h1><p>本地项目图片与上传入口。</p></div><label class="button button-primary"><Upload :size="16" />上传文件<input type="file" hidden multiple accept="image/jpeg,image/png,image/webp" @change="uploadMedia" /></label></header><section class="media-grid"><article v-for="item in (media.length?media:[{id:'hero',filename:'hero-circuit.jpg',url:'/assets/hero-circuit.jpg',mimeType:'image/jpeg'},{id:'work',filename:'workstation.jpg',url:'/assets/workstation.jpg',mimeType:'image/jpeg'}])" :key="item.id"><div class="media-thumb"><img :src="item.url" :alt="item.altText||item.filename" /></div><div><strong>{{item.filename}}</strong><span>{{item.mimeType}}</span></div></article></section></template>
      <template v-else-if="section==='comments'"><header class="admin-page-header"><div><span>COMMUNITY / MODERATION</span><h1>评论审核</h1><p>{{comments.filter(c=>c.status==='PENDING').length}} 条评论等待处理。</p></div></header><section class="admin-panel moderation-list"><article v-for="item in comments" :key="item.id"><div class="moderation-meta"><strong>{{item.authorName}}</strong><span class="risk-tag">{{item.status}}</span></div><p>{{item.content}}</p><small>文章：{{item.postSlug}}</small><div class="moderation-actions"><button class="button button-primary" @click="moderate(item,'APPROVED')"><Check :size="15" />通过</button><button class="button" @click="deleteComment(item)"><Trash2 :size="15" />拒绝</button></div></article></section></template>
      <template v-else-if="section==='users'"><header class="admin-page-header"><div><span>ACCESS / USERS</span><h1>用户与角色</h1><p>最小权限原则，关键变更写入操作日志。</p></div><button class="button button-primary"><Plus :size="16" />邀请用户</button></header><section class="admin-panel"><div class="admin-table user-table"><div class="table-head"><span>用户</span><span>角色</span><span>状态</span><span>最近登录</span><span>操作</span></div><div v-for="user in users" :key="user.id" class="table-row"><div><strong>{{user.name}}</strong><small>{{user.email}}</small></div><span>{{user.role}}</span><span>{{user.status}}</span><time>今天</time><button class="row-text-button" @click="user.status=user.status==='正常'?'已禁用':'正常'">{{user.status==='正常'?'禁用':'启用'}}</button></div></div></section></template>
      <template v-else-if="section==='settings'"><header class="admin-page-header"><div><span>SYSTEM / SETTINGS</span><h1>站点设置</h1><p>基础信息、分享模板和互动功能。</p></div><button class="button button-primary" @click="saveSettings"><Save :size="15" />保存设置</button></header><div v-if="saved" class="admin-success"><Check :size="15" />{{saved}}</div><div class="settings-grid"><section class="admin-panel settings-panel"><div class="panel-heading"><div><span>GENERAL</span><h2>基础信息</h2></div></div><label>站点名称<input v-model="settings.siteName" /></label><label>站点定位语<textarea v-model="settings.tagline" /></label></section><section class="admin-panel settings-panel"><div class="panel-heading"><div><span>SHARE / POSTER</span><h2>分享海报</h2></div></div><label>默认模板<select v-model="settings.shareTemplate"><option>横版卡片</option><option>竖版海报</option></select></label><div class="share-setting-preview"><span>SIGNAL NOTES</span><strong>{{settings.siteName}}</strong><small>{{settings.tagline}}</small><i>QR</i></div></section></div></template>
      <template v-else><header class="admin-page-header"><div><span>SYSTEM / AUDIT</span><h1>日志与备份</h1><p>每次重要变更都有记录，备份可验证且可以恢复。</p></div><button class="button button-primary" @click="backup='刚刚 · 校验通过'"><Archive :size="15" />立即备份</button></header><div class="log-status-grid"><div><ShieldCheck :size="20" /><span>安全检查</span><strong>全部通过</strong><small>最近检查：刚刚</small></div><div><Archive :size="20" /><span>最近备份</span><strong>{{backup}}</strong><small>数据库 + 媒体文件</small></div><div><Activity :size="20" /><span>异步任务</span><strong>0 失败</strong><small>最近 24 小时</small></div></div></template>
    </main>
  </div></div>
</template>
