<script setup>
import DOMPurify from 'dompurify'; import { marked } from 'marked';
import { ArrowRight, CalendarDays, ChevronRight, Clock3, FolderOpen, Hash } from 'lucide-vue-next';
import { computed, onMounted, onUnmounted, ref } from 'vue'; import { useRoute } from 'vue-router';
import BlogHeader from '../components/BlogHeader.vue'; import BlogFooter from '../components/BlogFooter.vue'; import SharePoster from '../components/SharePoster.vue';
import { formatDate, getAuthor, posts } from '../data'; import { apiRequest, submitComment } from '../api';

const route=useRoute();const post=ref(posts.find(p=>p.slug===route.params.slug));const comment=ref({name:'',content:''});const comments=ref([]);const commentStatus=ref('');
onMounted(async()=>{try{post.value=await apiRequest(`/posts/${route.params.slug}`);}catch{}document.title=post.value?`${post.value.title} | 脉冲笔记`:'文章未找到';window.addEventListener('scroll',progress,{passive:true});try{comments.value=await apiRequest(`/comments?postSlug=${route.params.slug}`);}catch{comments.value=JSON.parse(localStorage.getItem(`signal-comments-${route.params.slug}`)||'[]');}});
onUnmounted(()=>{document.title='脉冲笔记 | Signal Notes';window.removeEventListener('scroll',progress);document.documentElement.style.removeProperty('--reading-progress');});
function progress(){const h=document.documentElement.scrollHeight-window.innerHeight;document.documentElement.style.setProperty('--reading-progress',`${h?window.scrollY/h*100:0}%`);}
const author=computed(()=>getAuthor(post.value?.authorId));const article=computed(()=>{if(!post.value)return {html:'',headings:[]};const headings=[];const md=post.value.content.replace(/^## (.+)$/gm,(_,title)=>{const id=`section-${headings.length+1}`;headings.push({id,title});return `## <span id="${id}">${title}</span>`;});return {html:DOMPurify.sanitize(marked.parse(md)),headings};});
async function addComment(){if(!comment.value.name.trim()||comment.value.content.trim().length<2){commentStatus.value='请填写昵称和评论';return;}const payload={postSlug:post.value.slug,authorName:comment.value.name,content:comment.value.content};try{await submitComment(payload);}catch{const next=[{...payload,id:Date.now(),status:'PENDING',createdAt:new Date().toISOString()},...comments.value];comments.value=next;localStorage.setItem(`signal-comments-${post.value.slug}`,JSON.stringify(next));}comment.value={name:'',content:''};commentStatus.value='评论已提交，审核通过后会显示';}
</script>

<template><div class="blog-shell"><BlogHeader /><main v-if="post" class="article-page"><div class="article-breadcrumb"><RouterLink to="/blog">文章</RouterLink><ChevronRight :size="13" /><span>{{post.category}}</span></div><header class="article-header"><div class="article-category">{{post.category}}</div><h1>{{post.title}}</h1><p>{{post.excerpt}}</p><div class="article-byline"><span class="author-avatar">{{author.initials}}</span><div><strong>{{author.name}}</strong><span>{{formatDate(post.publishedAt)}} · {{post.readMinutes}} 分钟阅读</span></div><div class="article-stats"><span>{{post.views}} 阅读</span><span>更新于 {{post.updatedAt}}</span></div><SharePoster :post="post" /></div></header><figure class="article-cover"><img :src="post.cover" :alt="post.coverAlt" /><figcaption>{{post.coverAlt}}</figcaption></figure><div class="article-layout"><aside class="article-toc"><span>本页目录</span><nav><a v-for="(heading,index) in article.headings" :key="heading.id" :href="`#${heading.id}`"><small>0{{index+1}}</small>{{heading.title}}</a></nav></aside><article class="article-content" v-html="article.html" /><aside class="article-side"><div><Clock3 :size="16" /><span>{{post.readMinutes}} 分钟</span></div><div><CalendarDays :size="16" /><span>{{post.updatedAt}}</span></div><div><FolderOpen :size="16" /><span>{{post.category}}</span></div><div><Hash :size="16" /><span>{{post.tags.length}} 个标签</span></div></aside></div><footer class="article-footer"><div class="article-tags"><RouterLink v-for="tag in post.tags" :key="tag" :to="{path:'/blog/search',query:{q:tag}}">#{{tag}}</RouterLink></div><section class="comments"><div class="section-title"><span>DISCUSSION</span><h2>评论 <small>{{comments.length}}</small></h2></div><form class="comment-form" @submit.prevent="addComment"><div><label>昵称</label><input v-model="comment.name" placeholder="你的名字" /></div><div><label>评论</label><textarea v-model="comment.content" rows="4" placeholder="分享你的想法" /></div><button class="button button-primary">提交评论 <ArrowRight :size="16" /></button><small v-if="commentStatus">{{commentStatus}}</small></form><div class="comment-list"><article v-for="item in comments" :key="item.id"><div><strong>{{item.authorName||item.name}}</strong><span>{{(item.createdAt||item.date||'').slice(0,10)}} · {{item.status==='APPROVED'?'已通过':'待审核'}}</span></div><p>{{item.content}}</p></article><p v-if="!comments.length" class="comments-empty">还没有评论，欢迎留下第一条。</p></div></section><div class="article-author"><span class="author-avatar large">{{author.initials}}</span><div><span>WRITTEN BY</span><h2>{{author.name}}</h2><p>{{author.bio}}</p></div></div></footer></main><main v-else class="blog-main"><div class="not-found"><span>404 / LOST SIGNAL</span><h1>文章没有找到。</h1><RouterLink class="button button-primary" to="/blog">返回博客</RouterLink></div></main><BlogFooter /></div></template>
