<script setup>
import { ArrowRight, ChevronRight, Search } from 'lucide-vue-next';
import { computed, onMounted, ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import BlogHeader from '../components/BlogHeader.vue'; import BlogFooter from '../components/BlogFooter.vue';
import { formatDate, getAuthor } from '../data'; import { loadCategories, loadPosts, loadTags, subscribe, submitContact } from '../api';

const route=useRoute();const router=useRouter();const items=ref([]);const categories=ref([]);const tags=ref([]);const apiMode=ref('正在连接内容服务');const loading=ref(false);const draft=ref(route.query.q||'');const searchError=ref('');const email=ref('');const subStatus=ref('');const contact=ref({name:'',email:'',subject:'',message:'',consent:false});const contactStatus=ref('');
async function refreshPosts(){loading.value=true;try{const [value,categoryData,tagData]=await Promise.all([loadPosts(),loadCategories(),loadTags()]);items.value=Array.isArray(value)?value:[];categories.value=Array.isArray(categoryData)?categoryData:[];tags.value=Array.isArray(tagData)?tagData:[];apiMode.value='MySQL 实时数据';}catch(error){items.value=[];categories.value=[];tags.value=[];apiMode.value=`后端未连接 · ${error.message||'内容服务暂时不可用'}`;}finally{loading.value=false;}}
onMounted(refreshPosts);
watch(()=>route.query.q,(value)=>draft.value=value||'');
const section=computed(()=>route.path.split('/')[2]||'');const topic=computed(()=>route.query.topic||'');const routeSlug=computed(()=>route.params.slug||'');const routeAuthor=computed(()=>getAuthor(route.params.id));
const filtered=computed(()=>topic.value?items.value.filter(p=>p.category===topic.value||p.tags?.includes(topic.value)):items.value);
const searchResults=computed(()=>{const q=(route.query.q||'').toLowerCase();return q?items.value.filter(p=>[p.title,p.excerpt,p.category,...(p.tags||[]),p.content].join(' ').toLowerCase().includes(q)):[];});
const searchPage=computed(()=>Math.max(1,Number(route.query.page)||1));const searchPageSize=5;const searchPages=computed(()=>Math.max(1,Math.ceil(searchResults.value.length/searchPageSize)));const pagedSearchResults=computed(()=>searchResults.value.slice((Math.min(searchPage.value,searchPages.value)-1)*searchPageSize,Math.min(searchPage.value,searchPages.value)*searchPageSize));
function highlightedParts(text){const q=String(route.query.q||'').trim();if(!q)return [{text,match:false}];const lower=String(text||'').toLowerCase();const query=q.toLowerCase();const result=[];let from=0,index=lower.indexOf(query);while(index>=0){if(index>from)result.push({text:String(text).slice(from,index),match:false});result.push({text:String(text).slice(index,index+q.length),match:true});from=index+q.length;index=lower.indexOf(query,from);}if(from<String(text||'').length)result.push({text:String(text).slice(from),match:false});return result.length?result:[{text,match:false}];}
function doSearch(){const value=draft.value.trim();if(!value){searchError.value='请输入要查找的关键词';return;}if(value.length>80){searchError.value='关键词不能超过 80 个字符';return;}searchError.value='';router.push({path:'/blog/search',query:{q:value}});}
function goSearchPage(page){router.push({path:'/blog/search',query:{q:route.query.q,page}});}
async function doSubscribe(){if(!/^\S+@\S+\.\S+$/.test(email.value)){subStatus.value='请输入有效邮箱';return;}try{const result=await subscribe(email.value);subStatus.value=result.message||'订阅已保存';email.value='';}catch(error){subStatus.value=error.message||'订阅失败，请稍后重试';}}
async function doContact(){contactStatus.value='';if(!contact.value.name.trim()||!/^\S+@\S+\.\S+$/.test(contact.value.email)||!contact.value.subject.trim()||contact.value.message.trim().length<10||!contact.value.consent){contactStatus.value='请完整填写表单，并同意隐私说明';return;}try{const result=await submitContact({...contact.value,idempotencyKey:`contact-${Date.now()}`});contactStatus.value=`${result.message}，工单号 ${result.ticket}`;contact.value={name:'',email:'',subject:'',message:'',consent:false};}catch{contactStatus.value='提交失败，请稍后重试；已保留你填写的内容';}}
</script>

<template><div class="blog-shell"><BlogHeader /><main class="blog-main" :class="{'compact-main':section}">
  <template v-if="!section"><section class="blog-intro"><div><span class="page-index">INDEX / 001</span><h1>技术笔记<br />与长期观察</h1></div><p>记录软件、AI、系统与工具背后的结构和取舍。每一篇文章都尽量给出可以验证的上下文，而不只是结论。<small class="api-mode">{{ apiMode }}</small></p></section><section class="filter-bar"><button :class="{active:!topic}" @click="router.push('/blog')">全部 <span>{{items.length}}</span></button><button v-for="cat in categories" :key="cat.name" :class="{active:topic===cat.name}" @click="router.push({path:'/blog',query:{topic:cat.name}})">{{cat.name}} <span>{{cat.count}}</span></button></section><section class="post-list"><article v-for="(post,index) in filtered" :key="post.id" class="post-card" :class="{'is-large':index===0&&!topic}"><RouterLink class="post-card-cover" :to="`/blog/posts/${post.slug}`"><img :src="post.cover" :alt="post.coverAlt" /></RouterLink><div class="post-card-copy"><div class="post-meta"><span>{{post.category}}</span><span>{{formatDate(post.publishedAt)}}</span><span>{{post.readMinutes}} 分钟</span></div><h2><RouterLink :to="`/blog/posts/${post.slug}`">{{post.title}}</RouterLink></h2><p>{{post.excerpt}}</p><RouterLink class="read-link" :to="`/blog/posts/${post.slug}`">阅读全文 <ArrowRight :size="16" /></RouterLink></div></article></section><div class="list-end"><span>END OF NOTES</span><p>已经显示全部 {{filtered.length}} 篇文章</p></div>
  <button v-if="apiMode.includes('未连接')" class="data-retry" type="button" :disabled="loading" @click="refreshPosts">{{loading ? '正在重新连接…' : '重新连接内容服务'}}</button><section class="subscribe-box"><div><span>STAY IN SIGNAL</span><h2>每两周，收到一封有用的信。</h2><p>只发送新文章和真正值得分享的链接，不追踪打开行为。</p></div><form @submit.prevent="doSubscribe"><input v-model="email" type="email" placeholder="your@email.com" aria-label="邮箱地址" /><button>订阅 <ArrowRight :size="16" /></button><small v-if="subStatus">{{subStatus}}</small></form></section></template>
  <template v-else-if="section==='search'"><header class="page-heading"><span>SEARCH / 002</span><h1>搜索</h1><p>从标题、摘要、分类、标签和正文中查找。</p></header><form class="search-page-form" @submit.prevent="doSearch"><Search /><input v-model="draft" maxlength="81" placeholder="输入关键词，例如：可靠性" /><button>搜索</button></form><small v-if="searchError" class="form-error" role="alert">{{searchError}}</small><div v-if="route.query.q" class="search-summary">“{{route.query.q}}” 找到 {{searchResults.length}} 条结果 · 第 {{Math.min(searchPage,searchPages)}} / {{searchPages}} 页</div><section class="search-results"><article v-for="post in pagedSearchResults" :key="post.id"><div><span>{{post.category}}</span><span>{{formatDate(post.publishedAt)}}</span></div><h2><RouterLink :to="`/blog/posts/${post.slug}`"><template v-for="(part,index) in highlightedParts(post.title)" :key="index"><mark v-if="part.match">{{part.text}}</mark><template v-else>{{part.text}}</template></template></RouterLink></h2><p><template v-for="(part,index) in highlightedParts(post.excerpt)" :key="index"><mark v-if="part.match">{{part.text}}</mark><template v-else>{{part.text}}</template></template></p><RouterLink :to="`/blog/posts/${post.slug}`">查看文章 <ChevronRight :size="15" /></RouterLink></article></section><nav v-if="searchPages>1" class="result-pagination" aria-label="搜索结果分页"><button :disabled="searchPage<=1" @click="goSearchPage(searchPage-1)">上一页</button><button v-for="page in searchPages" :key="page" :class="{active:page===searchPage}" @click="goSearchPage(page)">{{page}}</button><button :disabled="searchPage>=searchPages" @click="goSearchPage(searchPage+1)">下一页</button></nav><div v-if="route.query.q&&!searchResults.length" class="empty-state"><span>NO SIGNAL</span><h2>没有找到相关内容</h2><p>尝试更短的关键词，或者从分类开始浏览。</p></div><div v-if="!route.query.q" class="search-suggestions"><h2>可以从这些主题开始</h2><button v-for="tag in tags.slice(0,8)" :key="tag.name" @click="router.push({path:'/blog/search',query:{q:tag.name}})">#{{tag.name}}</button></div></template>
  <template v-else-if="section==='categories'"><template v-if="routeSlug"><header class="page-heading"><span>TOPIC / 003</span><h1>{{routeSlug}}</h1><p>围绕这个主题的公开文章。</p></header><section class="post-list compact-post-list"><article v-for="post in items.filter(item=>item.category===routeSlug||item.category.toLowerCase()===routeSlug.toLowerCase())" :key="post.id" class="post-card"><div class="post-card-copy"><div class="post-meta"><span>{{post.category}}</span><span>{{formatDate(post.publishedAt)}}</span></div><h2><RouterLink :to="`/blog/posts/${post.slug}`">{{post.title}}</RouterLink></h2><p>{{post.excerpt}}</p></div></article></section></template><template v-else><header class="page-heading"><span>TOPICS / 003</span><h1>分类与标签</h1><p>沿着长期主题浏览，而不是被时间线推着走。</p></header><section class="category-grid"><RouterLink v-for="(cat,index) in categories" :key="cat.name" :to="{path:`/blog/categories/${encodeURIComponent(cat.name)}`}"><span>0{{index+1}}</span><h2>{{cat.name}}</h2><p>{{cat.description}}</p><small>{{cat.count}} 篇文章</small></RouterLink></section><section class="tag-cloud"><div class="section-title"><span>TAG INDEX</span><h2>全部标签</h2></div><div><RouterLink v-for="tag in tags" :key="tag.name" :to="{path:`/blog/tags/${encodeURIComponent(tag.name)}`}">#{{tag.name}} <small>{{tag.count}}</small></RouterLink></div></section></template></template>
  <template v-else-if="section==='tags'"><header class="page-heading"><span>TAG / 008</span><h1>#{{routeSlug}}</h1><p>所有带有这个标签的文章。</p></header><section class="post-list compact-post-list"><article v-for="post in items.filter(item=>item.tags?.includes(routeSlug))" :key="post.id" class="post-card"><div class="post-card-copy"><div class="post-meta"><span>{{post.category}}</span><span>{{formatDate(post.publishedAt)}}</span></div><h2><RouterLink :to="`/blog/posts/${post.slug}`">{{post.title}}</RouterLink></h2><p>{{post.excerpt}}</p></div></article></section></template>
  <template v-else-if="section==='authors'"><header class="page-heading"><span>AUTHOR / 009</span><h1>{{routeAuthor.name}}</h1><p>{{routeAuthor.role}} · {{items.filter(item=>item.authorId===route.params.id).length}} 篇文章</p></header><section class="about-page-grid"><div class="about-monogram">{{routeAuthor.initials}}<span>AUTHOR / EDITOR</span></div><div><p class="about-lead">{{routeAuthor.bio}}</p><section class="post-list compact-post-list"><article v-for="post in items.filter(item=>item.authorId===route.params.id)" :key="post.id" class="post-card"><div class="post-card-copy"><h2><RouterLink :to="`/blog/posts/${post.slug}`">{{post.title}}</RouterLink></h2><p>{{post.excerpt}}</p></div></article></section></div></section></template>
  <template v-else-if="section==='archives'"><header class="page-heading"><span>ARCHIVE / 004</span><h1>时间归档</h1><p>从 2026 年到现在，共 {{items.length}} 篇公开文章。</p></header><section class="archive-list"><div class="archive-year"><h2>2026</h2><div><RouterLink v-for="post in items" :key="post.id" :to="`/blog/posts/${post.slug}`"><time>{{post.publishedAt.slice(5).replace('-','.')}}</time><strong>{{post.title}}</strong><span>{{post.category}}</span><ArrowRight :size="17" /></RouterLink></div></div></section></template>
  <template v-else-if="section==='about'"><header class="page-heading"><span>ABOUT / 005</span><h1>写给愿意慢下来理解技术的人</h1></header><section class="about-page-grid"><div class="about-monogram">LM<span>AUTHOR / EDITOR</span></div><div><p class="about-lead">脉冲笔记是一个关于技术、系统和数字生活的独立写作项目。</p><p>这里的文章大多来自真实项目、代码阅读和长期使用工具之后的观察。比起追逐每一个新名词，我更关心一项技术解决了什么问题、引入了什么取舍。</p><div class="about-principles"><div><span>01</span><strong>来自实践</strong><p>给出可验证的上下文。</p></div><div><span>02</span><strong>承认边界</strong><p>区分事实与判断。</p></div><div><span>03</span><strong>长期可读</strong><p>减少热点语境。</p></div></div></div></section></template>
  <template v-else-if="section==='contact'"><header class="page-heading"><span>CONTACT / 006</span><h1>联系与内容反馈</h1><p>文章纠错、转载授权、合作或隐私问题，都可以通过表单提交。</p></header><section class="legal-page contact-page"><form class="contact-form" @submit.prevent="doContact"><label>姓名或昵称<input v-model="contact.name" maxlength="80" required /></label><label>邮箱<input v-model="contact.email" type="email" maxlength="180" required /></label><label>主题<input v-model="contact.subject" maxlength="180" required /></label><label>正文<textarea v-model="contact.message" rows="7" maxlength="2000" required placeholder="请提供文章链接和具体上下文，至少 10 个字。" /></label><label class="check-line"><input v-model="contact.consent" type="checkbox" />我同意联系信息按隐私说明处理</label><button class="button button-primary">提交反馈 <ArrowRight :size="16" /></button><small v-if="contactStatus" role="status">{{contactStatus}}</small></form><aside><span>PUBLIC EMAIL</span><h2>hello@signal-notes.local</h2><p>正常情况下会在 5 个工作日内回复。涉及安全漏洞时，请勿在公开评论中披露细节。</p><h2>转载与引用</h2><p>站内内容默认采用 CC BY-NC-SA 4.0；商业使用请提前联系获得书面许可。</p></aside></section></template>
  <template v-else-if="section==='privacy'"><header class="page-heading"><span>PRIVACY / 007</span><h1>隐私与使用说明</h1><p>最后更新：2026-08-15</p></header><article class="legal-page legal-copy"><section><h2>收集哪些信息</h2><p>评论时会保存昵称、可选邮箱、评论内容和提交时间；订阅时仅保存邮箱和确认状态。邮箱不会公开展示，也不会出售给第三方。</p></section><section><h2>Cookie 与本地数据</h2><p>站点仅使用本地存储保存主题偏好、入口页访问状态和离线演示数据，不用于跨站广告追踪。</p></section><section><h2>评论规范</h2><p>评论默认进入审核队列。垃圾信息、人身攻击、违法内容和泄露他人隐私的内容会被拒绝或删除。</p></section><section><h2>你的权利</h2><p>需要查询、更正或删除订阅和评论数据时，请通过联系页面发送请求。管理员会在核验关联信息后处理。</p></section><section><h2>使用协议</h2><p>文章仅用于知识交流，不构成法律、医疗或投资建议。引用时应保留作者与原文链接，不得歪曲原意。</p></section></article></template>
  <template v-else><div class="not-found"><span>404 / LOST SIGNAL</span><h1>这个页面没有找到。</h1><p>链接可能已经改变，或者文章暂时下线。</p><RouterLink class="button button-primary" to="/blog">返回博客</RouterLink></div></template>
</main><BlogFooter /></div></template>
